services:
  mongoDB:
    image: mongo:8
    container_name: ${MONGO_DB_NAME}
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INIT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INIT_PASSWORD}
    ports:
      - "${MONGO_DB_PORT}:${MONGO_DB_PORT}"
    networks:
      - seba_mongo_network
    volumes:
      - seba_mongo_data:/data/db
    healthcheck:
      test:
        [
          "CMD",
          "mongosh",
          "--port",
          "27017",
          "--eval",
          "db.adminCommand('ping')",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  mongoUI:
    image: mongo-express:1
    container_name: ${MONGO_DB_NAME}_ui
    restart: unless-stopped
    depends_on:
      mongoDB:
        condition: service_healthy
    ports:
      - "${MONGO_EXPRESS_PORT}:${MONGO_EXPRESS_PORT}"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_INIT_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_INIT_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_INIT_USER}:${MONGO_INIT_PASSWORD}@mongoDB:${MONGO_DB_PORT}/
    networks:
      - seba_mongo_network

networks:
  seba_mongo_network:
    driver: bridge

volumes:
  seba_mongo_data:
